// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

type Account struct {
	UserNumber   string
	ServerNumber string
	DiscordToken string
}

type ChannelNickname struct {
	UserNumber string
	ChannelID  int64
	Nickname   string
}

type NumbersMuted struct {
	UserNumber string
	Muted      int64
	Until      int64
}
